image: node:18

stages:
  - build
  - deploy

default:
  tags:
    - shell

build:
  stage: build
  interruptible: true
  script:
    - echo "Building deploy package"
    - which yarn || (npm install -g yarn) # Make sure yarn is installed
    - yarn --version # Check yarn version
    - yarn install --pure-lockfile # Use frozen-lockfile for CI environments
    - yarn build
    - echo "Build successful"
  artifacts:
    expire_in: 1 hour
    paths:
      - build
      - dist


deploy:
  stage: deploy
  interruptible: true
  script:
    - echo "Deploying to server"
    - mkdir -p /var/www/$CI_PROJECT_NAME
    - sudo rm -rf /var/www/$CI_PROJECT_NAME
    - cp -rv ./dist /var/www/$CI_PROJECT_NAME
    - echo "Deployed"

