stages:
  - build
  - deploy

default:
  tags:
    - shell

build:
  stage: build
  script:
    - echo "Building deploy package"
    # Используем NVM для установки правильной версии Node.js
    - source ~/.nvm/nvm.sh || true
    - nvm use 18 || nvm install 18
    - npm install -g yarn
    - yarn install
    - yarn build
    - echo "Build successful"
  artifacts:
    expire_in: 1 hour
    paths:
      - build
      - dist

deploy:
  stage: deploy
  script:
    - echo "Deploying to server"
    - mkdir -p /var/www/$CI_PROJECT_NAME
    - rm -rf /var/www/$CI_PROJECT_NAME || true
    - cp -rv ./dist /var/www/$CI_PROJECT_NAME
    - echo "Deployed"