stages:
  - build
  - deploy

default:
  tags:
    - shell

build:
  stage: build
  script:
    - echo "Building deploy package"
    - if ! command -v node &> /dev/null; then
        echo "Installing Node.js..."
        curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
        sudo apt-get install -y nodejs
      fi
    - node -v
    - if ! command -v yarn &> /dev/null; then
        echo "Installing Yarn..."
        sudo npm install -g yarn
      fi
    - yarn -v
    - yarn install
    - yarn build
    - echo "Build successful"
  artifacts:
    expire_in: 1 hour
    paths:
      - build
      - dist

deploy:
  stage: deploy
  script:
    - echo "Deploying to server"
    - sudo mkdir -p /var/www/$CI_PROJECT_NAME
    - sudo rm -rf /var/www/$CI_PROJECT_NAME
    - sudo cp -rv ./dist /var/www/$CI_PROJECT_NAME
    - sudo chown -R www-data:www-data /var/www/$CI_PROJECT_NAME
    - echo "Deployed"