image: node:18

stages:
  - build
  - deploy

default:
  tags:
    - shell

# variables:
#   BUILD_DIR: "dist"
#   DEPLOY_DIR: "/var/www/estoutic.ru/html"

build:
  stage: build
  interruptible: true
  script:
    - echo "Building deploy package"
    - yarn install 
    - yarn build
    - echo "Build successful"

  artifacts:
    expire_in: 1 hour
    paths:
      - build
      - dist


deploy:
  stage: deploy
  interruptible: true
  script:
    - echo "Deploying to server"
    - mkdir -p /var/www/$CI_PROJECT_NAME
    - sudo rm -rf /var/www/$CI_PROJECT_NAME
    - cp -rv ./dist /var/www/$CI_PROJECT_NAME
    - echo "Deployed"

