export enum BodyType {
    SUV_3_DOORS = "SUV_3_DOORS",
    SUV_5_DOORS = "SUV_5_DOORS",
    SEDAN = "SEDAN",
    COUPE = "COUPE",
    HATCHBACK_3_DOORS = "HATCHBACK_3_DOORS",
    HATCHBACK_5_DOORS = "HATCHBACK_5_DOORS",
    PICKUP_DOUBLE_CAB = "PICKUP_DOUBLE_CAB",
    PICKUP_SINGLE_CAB = "PICKUP_SINGLE_CAB",
    VAN = "VAN",
    MINIVAN = "MINIVAN",
  }